import { Product } from "./types";


export const products:Product[]=[
  {
    id:1,
    image:['/images/t-shirts/6.jpg'],
    title:'Blue Check Line T-Shirt',
    description:
  `  The "Blue Check Line T-Shirt" is a casual yet stylish garment featuring a blue checkered pattern. This t-shirt offers a blend of classic design with contemporary flair, perfect for adding a touch of sophistication to your everyday wardrobe.`,
    price:50,
    category:'T-Shirts',
    slug:'Check-Line-Shirt',
    size:['S', 'M','L','XL'],
    color:['#0C2D57','#000000','#A94438','#ffffff'],
    quantity:1,
    discount: 50,
    
  },
  
  {
  
    id:2,
    image:['/images/coat/1.jpg'],
    title:'Brown Coat For Winter',
    description:`
    Wrap up in style with our chic coat collection, offering warmth and fashion-forward designs for any occasion.`,
    price:200,
    category:'Coats',
    slug:'Winter-Coat',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#994D1C'],
    quantity:1,
    discount:0,
    
  },
  {
    
      id:3,
      image:['/images/accessories/Butterfly Bracelet in Solid Sterling Silver Purple, Green or Yellow, Elegant, Feminine.jpg'],
      title:'Bracelet in Solid',
      description:`
      Indulge in elegance with our Butterfly Bracelet crafted from Solid Sterling Silver. Available in striking shades of Purple, Green, or Yellow, this accessory exudes femininity and charm. Adorn your wrist with a touch of sophistication and grace, perfect for adding a whimsical yet refined accent to any ensemble.`,
      price:60,
      category:'Accessories',
      slug:'Fancy-Bracelet',
      size:['S', 'M','L','XL'],
      color:['#000000','#D0A2F7','#BEADFA','#F5F7F8'],
      quantity:1,
      discount:30,
     
    },
    
  
  {
    id:4,
    image:["/images/shoes/Women's Shoes, Heels, Boots _ Modcloth (1).jpg"],
    title:'Blue Fancy Shoes',
    description:`
    Discover Modcloth's stylish women's footwear collection, featuring a variety of shoes, heels, and boots for every taste and occasion.`,
    price:80,
    category:'Shoes',
    slug:'Blue-Shoes',
    size:['5', '6','6.5','7','7.5','8','9'],
    color:['#ffffff','#000000','#e60000'],
    quantity:1,
    discount:0,
    
    
  },
  
  {
    id:5,
    image:["/images/purfumes/expensive.jpg"],
    title:'Moon Paris Purfume',
    description:'Expensive purfumes Best Gift For Wedding',
    price:200,
    category:'Purfumes',
    slug:'Moon-Paris-Purfume',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#FDE5D4'],
    quantity:1,
    discount:70,
    
  },
  {
    id:6,
    image:["/images/bags/download (11).jpg"],
    title:'Light Pink Leather Fancy Bag',
    description:`Elevate your style with our light pink leather bag. Featuring intricate detailing and a touch of femininity, this fancy accessory adds sophistication to any outfit. Perfect for any occasion, it offers ample space for your essentials while making a chic statement.`,
    price:100,
    category:'Bags',
    slug:'Light-Pink-Leather-Fancy-Bag',
    size:['S', 'M','L','XL'],
    color:['#F2E8C6','#FFB7B7','#F8F0E5'],
    quantity:1,
    discount:0,
    
  },
  {
    id:7,
    image:["/images/bags/Letter Graphic Metal Handle Novelty Bag.jpg"],
    title:'Fancy Sea Green Bag',
    description:
    'The "Letter Graphic Metal Handle Novelty Bag" is a stylish and unique handbag featuring a distinctive design with letter graphics and a metal handle. It is likely to be a fashion-forward accessory, combining modern aesthetics with functionality.',
    price:150,
    category:'Bags',
    slug:'Fancy-Sea-Green-Bag',
    size:['S', 'M','L'],
    color:['#B0C5A4','#000000','#F2ECBE'],
    quantity:1,
    discount:30,
   
  },
  {
    id:8,
    image:["/images/t-shirts/1.jpg"],
    title:'Blue Check Line T-shirt',
    description:'Effortlessly stylish, our Blue Check Line T-shirt combines classic checkered charm with modern comfort.',
    price:70,
    category:'T-Shirts',
    slug:'Blue-Check-Line-Shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#337CCF','#279EFF'],
    quantity:1,
    discount:0,
   
  },
  {
    id:9,
    image:["/images/t-shirts/3.jpg"],
    title:'Snake Like T-Shirt',
    description:'Channel your inner wild with our Snake-Like T-shirt, boasting a striking scale-inspired pattern for a bold and edgy look',
    price:100,
    category:'T-Shirts',
    slug:'Snake-Like-T-Shirt',
    size:['S', 'M','L','XL','XXL'],
    color:['#65451F','#000000','#9288F8'],
    quantity:1,
    discount:0,
    
    
  },
  {
    id:10,
    image:['/images/t-shirts/4.jpg'],
    title:'Black Lining T-shirt',
    description:'Effortlessly chic, our Black Lining T-shirt features subtle black lining details for a touch of sophistication, crafted from soft, breathable fabric for everyday comfort.',
    price:100,
    category:'T-Shirts',
    slug:'Balck-Lining-T-shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#e60000'],
    quantity:1,
    discount: 50,
    
  },
  {
    id:11,
    image:['/images/t-shirts/5.jpg'],
    title:'Light Pink with dotted circle',
    description:'Add a playful touch to your wardrobe with our Light Pink Dotted Circle T-shirt, crafted for comfort and charm.',
    price:110,
    category:'T-Shirts',
    slug:'Light-Pink-T-Shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#FFD1DA','#DFA87'],
    quantity:1,
    discount: 0,
    
  },
  {
    id:12,
    image:['/images/t-shirts/6.jpg'],
    title:'Red Shirt with Black Lines',
    description:`Make a statement with our Red T-shirt featuring a bold black line detail. Crafted for both style and comfort, this tee adds a modern edge to your casual ensemble. Perfect for any occasion, it's a versatile wardrobe essential that demands attention.`,
    price:70,
    category:'T-Shirts',
    slug:'Red-Shirt',
    size:['S', 'M','L','XL'],
    color:['#8C3333','#000000','#C51605'],
    quantity:1,
    discount: 40,
   
  },
  {
    id:13,
    image:['/images/t-shirts/7.jpg'],
    title:'White T-Shirt',
    description:'Classic yet bold, our White T-shirt with a Black Line detail offers versatile style and comfort for everyday wear.',
    price:100,
    category:'T-Shirts',
    slug:'White-T-Shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000'],
    quantity:1,
    discount: 0,
    
  },
  {
    id:14,
    image:["/images/bags/download (12).jpg"],
    title:'Sky Blue Fancy Bag',
    description:'Leather Women Bag For Function',
    price:120,
    category:'Bags',
    slug:'Sky-Blue-Fancy-Bag',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#94ADD7','#071952'],
    quantity:1,
    discount:40,
    
  },
  {
    id:15,
    image:["/images/bags/GUESS_ Global Lifestyle Brand for Women, Men and Kids.jpg"],
    title:'Black Sequare Fancy Bag',
    description:'Sleek and sophisticated, our Black Square Fancy Bag is the perfect accessory to elevate any outfit with timeless elegance.',
    price:100,
    category:'Bags',
    slug:'Black-Sequare-Fancy-Bag',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000'],
    quantity:1,
    discount:0,
   
  },
  {
    id:16,
    image:["/images/bags/Shoes & Bags For Men & Women _ Cheap Best Shoes & Bags Online Sale.jpg"],
    title:'Dark Pink Shaded Bag',
    description:'"Accessorize boldly with our Dark Pink Shaded Bag, a vibrant and versatile piece to elevate any outfit.',
    price:90,
    category:'Bags',
    slug:'Dark-Pink-Shaded-Bag',
    size:['S', 'M','L','XL'],
    color:['#B04759','#000000','#C07F00'],
    quantity:1,
    discount:60,
    
  },
  {
    id:17,
    image:["/images/bags/Shoulder Bags _ PEDRO.jpg"],
    title:'Light Pink with long Chain Bag',
    description:'Chic and versatile, our Light Pink Long Chain Bag adds elegance to any outfit, perfect for day or evening wear.',
    price:150,
    category:'Bags',
    slug:'Light-Pink-Long-Chain',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#FEA1A1','#FDCEDF'],
    quantity:1,
    discount:0,
    
  },
  {
    id:18,
    image:["/images/purfumes/download (15).jpg"],
    title:"Victoria's Secret ",
    description:`"Experience allure with Victoria's Secret Perfume, a blend of sophistication and sensuality in every scent.`,
    price:100,
    category:'Purfumes',
    slug:"Victoria's--Pufume-Secret",
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#DB005B'],
    quantity:1,
    discount:0,
    
  },
  {
    id:19,
    image:["/images/purfumes/download (16).jpg"],
    title:'Rose Purfume ',
    description:'"Embrace romance with our Rose Perfume, a timeless scent capturing the essence of femininity.',
    price:150,
    category:'Purfumes',
    slug:'Lady-Purfumes',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#2B2730','#FFDEDE'],
    quantity:1,
    discount:0,
    
  },
  {
    id:20,
    image:["/images/purfumes/PURE XS FOR HER edp spray 80 ml.jpg"],
    title:'Pure XS ',
    description:'Experience allure with Pure XS, a bold and captivating fragrance that leaves a lasting impression.',
    price:80,
    category:'Purfumes',
    slug:'Pure-XS-Purfume',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#ED7B7B','#CE5A67'],
    quantity:1,
    discount:0,
    
  },
  {
    id:21,
    image:["/images/purfumes/kismat angel.jpg"],
    title:'Kismat Angel',
    description:'Discover enchantment with Kismat Angel, a fragrance inspired by celestial beauty and grace.',
    price:150,
    category:'Purfumes',
    slug:'Kismat-Angel',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#F2BE22'],
    quantity:1,
    discount:50,
    
  },
  {
    id:22,
    image:["/images/purfumes/f447aa0c9e2a10d38793e5b8e9f53f5c.jpg"],
    title:'Amouage',
    description:'Expensive purfumes Best Gift For Wedding',
    price:200,
    category:'Purfumes',
    slug:'Amouage-Purfume',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#C27664','#EAD196'],
    quantity:1,
    discount:0,
    
  },
  {
    id:23,
    image:['/images/coat/2.jpg'],
    title:'Black Long Coat',
    description:'Stay sleek and warm with our Black Long Coat, offering timeless sophistication for any occasion.',
    price:150,
    category:'Coats',
    slug:'Black-Coat',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#F8EDFF','#000000'],
    quantity:1,
    discount:0,
   
  },
  {
    id:24,
    image:['/images/coat/8a1378a81883c8277f97f8fe20913048.jpg'],
    title:'Gray Elegent Coat',
    description:'Effortlessly stylish, our Gray Coat offers timeless elegance and versatility for any occasion.',
    price:200,
    category:'Coats',
    slug:'Gray-Elegent-Coat',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#F8EDFF','#F5F7F8','#000000'],
    quantity:1,
    discount:30,
    
  },
  {
    id:25,
    image:['/images/coat/brown.jpg'],
    title:'Brown Coat',
    description:'Classic and versatile, our Brown Coat offers timeless style for any occasion.',
    price:130,
    category:'Coats',
    slug:'brown-Coat',
    size:['S', 'M','L','XL'],
    color:['#862B0D','#000000','#AE431E'],
    quantity:1,
    discount:0,
    
  },
  {
    id:26,
    image:['/images/coat/red.jpg'],
    title:'Mehron Short Coat',
    description:'Sophisticated and stylish, our Mehron Short Coat offers both warmth and elegance for any occasion.',
    price:100,
    category:'Coats',
    slug:'Mehron-Coat',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#7D0A0A'],
    quantity:1,
    discount:30,
   
  },
  {
    id:27,
    image:["/images/coat/Women's Blue Wool Trench Coat _ Trench Coat _ Wool Trench Coat.jpg"],
    title:'Blue Wool Trench Coat',
    description:'Wrap up in style with our Blue Wool Trench Coat, blending timeless sophistication with modern comfort.',
    price:170,
    category:'Coats',
    slug:'Blue-Wool-Coat',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#0C2D57'],
    quantity:1,
    discount:40,
    
  },
  {
    
    id:28,
    image:['/images/accessories/download (9).jpg'],
    title:'Necklace with Earing Set',
    description:'"Complete your ensemble with our elegant Necklace with Earrings Set, perfect for adding glamour to any look. ',
    price:180,
    category:'Accessories',
    slug:'neckalce',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#F0F3FF','#F8F4EC'],
    quantity:1,
    discount:50,
   
  },
  {
    
    id:29,
    image:['/images/accessories/download (10).jpg'],
    title:'Circle Necklace Set with Bracelet',
    description:'Complete your look with our Circle Necklace Set including a coordinating bracelet, for effortless elegance. ',
    price:200,
    category:'Accessories',
    slug:'circle-necklace-set',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#F0F3FF','#F8F4EC'],
    quantity:1,
    discount:0,
    
  },
  {
    
    id:30,
    image:['/images/accessories/Fancitaste.jpg'],
    title:'Dark Green Pearl Fancy Ring',
    description:'Adorn your finger with elegance in our Dark Green Pearl Fancy Ring, a statement piece for any occasion. ',
    price:100,
    category:'Accessories',
    slug:'Ring',
    size:['S', 'M','L','XL'],
    color:['#1A4D2E','#1F441E','#000000'],
    quantity:1,
    discount:20,
    
  },
  {
    
    id:31,
    image:['/images/accessories/Junwei Replacement Beaded Bracelet for Apple Watch Band 41mm,40mm,38mm,45mm,44mm,42mm,Adjustable Stylish Bands with Bling Rhinestones,Crystal,Pearls for iWatch Series 7,6,SE,5,4,3,2,1,Women,Girls.jpg'],
    title:'Junwei Beaded Apple Watch Bracelet',
    description:'Elevate your Apple Watch with our stylish beaded bracelet replacement. Offering a unique blend of fashion and function, this bracelet adds a touch of elegance to your wristwear. ',
    price:80,
    category:'Accessories',
    slug:'apple-watch',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#e60000'],
    quantity:1,
    discount:0,
    
  },
  {
    
    id:32,
    image:['/images/accessories/Our Favorite Things on Sale to Buy for Your Wedding - Bridal Musings.jpg'],
    title:'Silver Drop Earings',
    description:'Enhance your style with our Silver Drop Earrings, a versatile and elegant addition to any outfit. ',
    price:60,
    category:'Accessories',
    slug:'Silver-drop-earings',
    size:['S', 'M','L','XL'],
    color:['#FCECDD','#EE99A0','#E28F83'],
    quantity:1,
    discount:0,
   
  },
  {
    
    id:33,
    image:['/images/accessories/Promise Rings_ 22 The Most Popular Ring Ideas For Your Love.jpg'],
    title:'Butterfly Silver and Golden Rings',
    description:'Flutter into elegance with our Butterfly Silver & Gold Rings, delicately crafted for timeless charm. ',
    price:100,
    category:'Accessories',
    slug:'Silver-golden-Ring',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#EBEBEB','#FFE196'],
    quantity:1,
    discount:30,
    
  },
  {
    
    id:34,
    image:["/images/accessories/Stone and strand-fine jeewlery foerevery little and big win.jpg"],
    title:'Stone and Strand Jewelry',
    description:"Elevate your moments with Stone and Strand's fine jewelry, crafted for every occasion, big or small.",
    price:120,
    category:'Accessories',
    slug:'Stone-ans-stand-jewlery',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#F4E8C1','#FFE196'],
    quantity:1,
    discount:0,
   
  },
  {
    
    id:35,
    image:["/images/accessories/1.jpg"],
    title:'Butterfly Necklace',
    description:'Butterfly necklace  in Solid Sterling blue,pink ',
    price:150,
    category:'Accessories',
    slug:'butterfly-necklace',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#e60000'],
    quantity:1,
    discount:30,
  
  },
  {
    id:36,
    image:["/images/shoes/download (13).jpg"],
    title:'Silver Fancy Shoes',
    description:'Step into elegance with our Silver Fancy Shoes, crafted for sophistication and style.',
    price:100,
    category:'Shoes',
    slug:'Shiny-Shoes',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#ffffff','#F2F2F2','#F6C667'],
    quantity:1,
    discount:0,
  
    
  },
  {
    id:37,
    image:["/images/shoes/Joskaa  2022 Women Shoe Designer Pump Square Heel for Summer Dancing Party Wedding Sandal Chaussure - Apricot _ 38.jpg"],
    title:'Pump Square Hel in whitish',
    description:'"Step out in style with our Whitish Square Heel Pumps, blending elegance with comfort',
    price:80,
    category:'Shoes',
    slug:'Pump-Square-Heel',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#ffffff','#FDFCFC','#F9F5F0'],
    quantity:1,
    discount:0,
   
    
  },
  {
    id:38,
    image:["/images/shoes/Rhinestone Decor Point Toe Back Zipper Flats.jpg"],
    title:'Black Fancy Shoes',
    description:'Sophisticated and chic, our Black Fancy Shoes elevate any outfit with elegance and flair.',
    price:100,
    category:'Shoes',
    slug:'Point-Toe-Back-Zipper-Flats',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#ffffff','#000000'],
    quantity:1,
    discount:0,
  
    
  },
  {
    id:39,
    image:["/images/shoes/Shop Vintage Outfits __ Vintage Style Clothing __ ModCloth™ (1).jpg"],
    title:'Red Shoes',
    description:'Make a statement with our vibrant Red Shoes, perfect for any occasion',
    price:80,
    category:'Shoes',
    slug:'Vintage-Shoes',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#DD3E3E','#A21232','#000000'],
    quantity:1,
    discount:30,
   
    
  },
  {
    id:40,
    image:["/images/shoes/Shop Vintage Outfits __ Vintage Style Clothing __ ModCloth™.jpg"],
    title:'Purplish Shoes',
    description:'Stand out in style with our Purplish Shoes, perfect for any occasion.',
    price:70,
    category:'Shoes',
    slug:'purplish-shoes',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#ffffff','#000000','#4D3664'],
    quantity:1,
    discount:0,
   
    
  },
  {
    id:41,
    image:["/images/shoes/Women's Shoes, Heels, Boots _ Modcloth.jpg"],
    title:'Blue Party Wear Shoes',
    description:'Dance the night away in style with our Blue Party Wear Shoes',
    price:100,
    category:'Shoes',
    slug:'blue-party-wear-shoes',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#ffffff','#000000','#0E3047'],
    quantity:1,
    discount:40,
    
    
  },
  {
    id:42,
    image:['/images/t-shirts/881c4aea3cbf0f68c0ecea9b45206053.jpg'],
    title:'Sky Blue Butterfly Neck T-shirt',
    description:'Flutter into style with our Sky Blue Butterfly Neck T-shirt, combining charm and comfort.',
    price:100,
    category:'T-Shirts',
    slug:'sky-blue-tshirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#E2EFF1','#B2EBF9'],
    quantity:1,
    discount: 30,
    
  },
  {
    id:43,
    image:['/images/t-shirts/962e7c17fc9e9e43345b4df4bd910046.jpg'],
    title:'Mehron Net Sleves T-Shirt',
    description:"Upgrade your style with our Mehron Net Sleeves T-shirt, adding sophistication to your casual look",
    price:100,
    category:'T-Shirts',
    slug:'mehron-shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#990000'],
    quantity:1,
    discount: 30,
    
  },
  {
    id:44,
    image:["/images/t-shirts/96711d90010d5d01a5ab10fcb7ef2126.jpg"],
    title:'Ligth Pink Shirt',
    description:"Attractive And Classy Office Wear Beautiful T-Shirt For Business Women's",
    price:350,
    category:'T-Shirts',
    slug:'Ligth-Pink-Shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#C05C7E'],
    quantity:1,
    discount:60,
   
  },
  {
    id:45,
    image:["/images/t-shirts/1f29d8c592592aacc18662cab7ea5b8a.jpg"],
    title:'White-Black Shirt',
    description:` A sleek and modern shirt with crisp white fabric and bold black designs, perfect for adding a sharp edge to any outfit.`,
    price:350,
    category:'T-Shirts',
    slug:'White-Black-Shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000'],
    quantity:1,
    discount:60,
   
  },
  {
    id:46,
    image:["/images/t-shirts/4beab44fe8794ad9ade0c882061c885e.jpg"],
    title:'Dark Green Shirt with Golded Leaves',
    description:` 
    A striking dark green shirt adorned with elegant lines of golden leaves, exuding a touch of natural beauty and sophistication.`,
    price:350,
    category:'T-Shirts',
    slug:'Check-Line-Shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#04322E'],
    quantity:1,
    discount:60,
   
  },
  {
    id:47,
    image:["/images/t-shirts/1796b1111db858b3958a02a15d5daab6.jpg"],
    title:'Fancy Black Shirt For Function',
    description:` 
    Make a statement at any function with our Fancy Black Shirt, exuding sophistication and style.`,
    price:80,
    category:'T-Shirts',
    slug:'fancy-balck-Shirt',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000'],
    quantity:1,
    discount:0,
   
  },
  {
    id:48,
    image:["/images/shoes/ab0b1138d7e1ac66d65349fb3cfb947c.jpg"],
    title: 'Mehndi Shoes',
    description:'Complete your Mehndi look with our stylish Shoes featuring a decorative strip.',
    price:100,
    category:'Shoes',
    slug:'mehndi-shoes',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#ffffff','#000000','#0E3047'],
    quantity:1,
    discount:40,
    
    
  },
  
  {
    
    id:49,
    image:["/images/accessories/c115b6d183b8e02a0ceee5451a55269e.jpg"],
    title:'GUCCI Watch',
    description:'Make a statement of luxury and sophistication with our iconic GUCCI Watch. Crafted with meticulous attention to detail, this timepiece showcases the epitome of elegance and style.  ',
    price:120,
    category:'Accessories',
    slug:'GUCCI-Watch',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#F4E0B9','#000000'],
    quantity:1,
    discount:0,
  
  },
  {
    id:50,
    image:["/images/coat/winter fashion 2023 winter 2023 fashion trends fashion.jpg"],
    title:'Black Long Coat',
    description:`Embrace timeless sophistication with our Black Long Coat. Crafted from high-quality materials, this coat offers both style and warmth. With its sleek design and versatile silhouette, it's the perfect outerwear staple for any wardrobe. `,
    price:150,
    category:'Coats',
    slug:'black-Coat',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000'],
    quantity:1,
    discount:60,
    
  },
  {
    id:51,
    image:["/images/bags/291c1d96425cc777d8040a6368a348a1.jpg"],
    title:'Gray Bg',
    description:'Add a touch of versatility to your ensemble with our Gray Bag. Crafted with durable materials and a sleek design, this bag is perfect for everyday use. ',
    price:80,
    category:'Bags',
    slug:'Gray-Bag',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#EEEDED','#FAF2D3'],
    quantity:1,
    discount:0,
    
  },
  {
    id:52,
    image:["/images/purfumes/76d5c6b1bea0f2f678a52eea811b22b1.jpg"],
    title:'BOTEEGA VENETA',
    description:'Indulge in luxury with our BOTTEGA VENETA Perfume. Impeccably crafted with the finest ingredients, this fragrance captures the essence of Italian elegance and sophistication. ',
    price:200,
    category:'Purfumes',
    slug:'boteega-veneta',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#EA906C','#A86464'],
    quantity:1,
    discount:50,
    
  },
  {
    id:53,
    image:["/images/t-shirts/c78d3abe6ab46024fc65f53b8cab0d14.jpg"],
    title:'Silk Light Brown T-Shirt',
    description:` 
    Elevate your wardrobe with our Silk Light Brown T-Shirt. Crafted from luxurious silk fabric, this shirt offers both comfort and sophistication.`,
    price:70,
    category:'T-Shirts',
    slug:'Silk-Shirt',
    size:['S', 'M','L','XL'],
    color:['#AD8E70','#CDB699','#000000'],
    quantity:1,
    discount:0,
   
  }
  ,{
    id:54,
    image:["/images/shoes/28268f1f83b2a9ed8133c8f3420e567b.jpg"],
    title: 'Mehron Shinty Shoes',
    description:'Complete your Mehndi look with our stylish Shoes featuring a decorative strip.',
    price:150,
    category:'Shoes',
    slug:'mehndi-shoes',
    size:['5', '6','6.5','7','7.5','8'],
    color:['#000000','#99154E','#8E0505'],
    quantity:1,
    discount:60,
    
    
  },

]
    

  

    