import { Product } from "./types";


export const products:Product[]=[{
  id:1,
  image:['/images/t-shirts/2.jpg'],
  title:'Blue Check Line T-Shirt',
  description:'Best Qualiy T-shirt for Women',
  price:100,
  category:'T-Shirts',
  slug:'Check-Line-Shirt',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount: 50,
  uID: ''
},
{
  id:2,
  image:['/images/coat/1.jpg'],
  title:'Brown Coat For Winter',
  description:'Stay cozy and chic with our collection of coats',
  price:200,
  category:'Coats',
  slug:'Winter-Coat',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
},
{
  
    id:3,
    image:['/images/accessories/Butterfly Bracelet in Solid Sterling Silver Purple, Green or Yellow, Elegant, Feminine.jpg'],
    title:'Bracelet in Solid',
    description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
    price:200,
    category:'Accessories',
    slug:'Fancy-Braclet',
    size:['S', 'M','L','XL'],
    color:['#ffffff','#000000','#e60000'],
    quantity:1,
    discount:60,
    uID:''
  },
  

{
  id:4,
  image:["/images/shoes/Women's Shoes, Heels, Boots _ Modcloth (1).jpg"],
  title:'Mehron Fancy Shoes',
  description:'Top Notch Shoes for Women',
  price:100,
  category:'Shoes',
  slug:'Blue-Shoes',
  size:['5', '6','6.5','7','7.5','8'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
  
},

{
  id:5,
  image:["/images/purfumes/expensive.jpg"],
  title:'Moon Paris Purfume',
  description:'Expensive purfumes Best Gift For Wedding',
  price:200,
  category:'Purfumes',
  slug:'Expensive-Purfumes',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:70,
  uID:''
},
{
  id:6,
  image:["/images/bags/download (11).jpg"],
  title:'Fancy Sea Green Bag',
  description:'Leather Women Bag For Function',
  price:350,
  category:'Bags',
  slug:'Bags',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
},
{
  id:7,
  image:["/images/bags/Letter Graphic Metal Handle Novelty Bag.jpg"],
  title:'Fancy Sea Green Bag',
  description:'Leather Women Bag For Function',
  price:350,
  category:'Bags',
  slug:'Fancy-Bags',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:20,
  uID:''
},
{
  id:8,
  image:["/images/t-shirts/1.jpg"],
  title:'Blue Check lIne T-shirt',
  description:'Wear in Summer',
  price:350,
  category:'T-Shirts',
  slug:'Check-Line-Shirt',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  id:9,
  image:["/images/t-shirts/3.jpg"],
  title:'Snake Like T-Shirt',
  description:'Wear in Summer',
  price:100,
  category:'T-Shirts',
  slug:'Snake-Like-T-Shirt',
  size:['S', 'M','L','XL','XXL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
  
},
{
  id:10,
  image:['/images/t-shirts/4.jpg'],
  title:'Blue Check Line T-Shirt',
  description:'Best Qualiy T-shirt for Women',
  price:100,
  category:'T-Shirts',
  slug:'Check-Shirt',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount: 50,
  uID: ''
},
{
  id:11,
  image:['/images/t-shirts/5.jpg'],
  title:'Blue Check Line T-Shirt',
  description:'Best Qualiy T-shirt for Women',
  price:100,
  category:'T-Shirts',
  slug:'Line-Shirt',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount: 0,
  uID: ''
},
{
  id:12,
  image:['/images/t-shirts/6.jpg'],
  title:'Blue Check Line T-Shirt',
  description:'Best Qualiy T-shirt for Women',
  price:100,
  category:'T-Shirts',
  slug:'Shirt',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount: 30,
  uID: ''
},
{
  id:13,
  image:['/images/t-shirts/7.jpg'],
  title:'Blue Check Line T-Shirt',
  description:'Best Qualiy T-shirt for Women',
  price:100,
  category:'T-Shirts',
  slug:'t-Shirts',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount: 50,
  uID: ''
},
{
  id:14,
  image:["/images/bags/download (12).jpg"],
  title:'Sea Green Bag',
  description:'Leather Women Bag For Function',
  price:350,
  category:'Bags',
  slug:'Hang-Bag',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
},
{
  id:15,
  image:["/images/bags/GUESS_ Global Lifestyle Brand for Women, Men and Kids.jpg"],
  title:'Sea Green Bag',
  description:'Leather Women Bag For Function',
  price:350,
  category:'Bags',
  slug:'Brand-Bag',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
},
{
  id:16,
  image:["/images/bags/Shoes & Bags For Men & Women _ Cheap Best Shoes & Bags Online Sale.jpg"],
  title:'Sea Green Bag',
  description:'Leather Women Bag For Function',
  price:350,
  category:'Bags',
  slug:'Cheap-Best-Bag',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
},
{
  id:17,
  image:["/images/bags/Shoulder Bags _ PEDRO.jpg"],
  title:'Sea Green Bag',
  description:'Leather Women Bag For Function',
  price:350,
  category:'Bags',
  slug:'Shoulder-Bag',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
},
{
  id:18,
  image:["/images/purfumes/download (15).jpg"],
  title:'Moon Paris Purfume',
  description:'Expensive purfumes Best Gift For Wedding',
  price:200,
  category:'Purfumes',
  slug:'Lady-Purfume',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:70,
  uID:''
},
{
  id:19,
  image:["/images/purfumes/download (16).jpg"],
  title:'Moon Paris Purfume',
  description:'Expensive purfumes Best Gift For Wedding',
  price:200,
  category:'Purfumes',
  slug:'Lady-Purfumes',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:70,
  uID:''
},
{
  id:20,
  image:["/images/purfumes/Gucci refreshes Bamboo fragrance via liberating campaign.jpg"],
  title:'Moon Paris Purfume',
  description:'Expensive purfumes Best Gift For Wedding',
  price:200,
  category:'Purfumes',
  slug:'GUCCI-Purfume',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:70,
  uID:''
},
{
  id:21,
  image:["/images/purfumes/Lady million.jpg"],
  title:'Moon Paris Purfume',
  description:'Expensive purfumes Best Gift For Wedding',
  price:200,
  category:'Purfumes',
  slug:'Lady-Milliom-Purfume',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:70,
  uID:''
},
{
  id:22,
  image:["/images/purfumes/PURE XS FOR HER edp spray 80 ml.jpg"],
  title:'Moon Paris Purfume',
  description:'Expensive purfumes Best Gift For Wedding',
  price:200,
  category:'Purfumes',
  slug:'Pure-Purfume',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:70,
  uID:''
},
{
  id:23,
  image:['/images/coat/2.jpg'],
  title:'Brown Coat For Winter',
  description:'Stay cozy and chic with our collection of coats',
  price:200,
  category:'Coats',
  slug:'Coat',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
},
{
  id:24,
  image:['/images/coat/3.jpg'],
  title:'Brown Coat For Winter',
  description:'Stay cozy and chic with our collection of coats',
  price:200,
  category:'Coats',
  slug:'Winter-Coats',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
},
{
  id:25,
  image:['/images/coat/Double Breasted Wool Coat, Blue Wool Coat, Warm Coat, Winter Coat, Womens Coat, Long Wool Coat, Plated Coat, Handmade Coat C1596 - Etsy.jpg'],
  title:'Brown Coat For Winter',
  description:'Stay cozy and chic with our collection of coats',
  price:200,
  category:'Coats',
  slug:'Wool-Coat',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
},
{
  id:26,
  image:['/images/coat/Vintage Inspired Blue Long Wool Coat Women, Winter Coat, Fit and Flare Coat, Double Breasted Coat, Princess Coat, Custom Coat Xiaolizi 3127.jpg'],
  title:'Brown Coat For Winter',
  description:'Stay cozy and chic with our collection of coats',
  price:200,
  category:'Coats',
  slug:'Blue-Long-Coat',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
},
{
  id:27,
  image:["/images/coat/Women's Blue Wool Trench Coat _ Trench Coat _ Wool Trench Coat.jpg"],
  title:'Brown Coat For Winter',
  description:'Stay cozy and chic with our collection of coats',
  price:200,
  category:'Coats',
  slug:'Blue-Wool-Coat',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:0,
  uID:''
},
{
  
  id:28,
  image:['/images/accessories/download (9).jpg'],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Braclet',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  
  id:29,
  image:['/images/accessories/download (10).jpg'],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Braclet',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  
  id:30,
  image:['/images/accessories/Fancitaste.jpg'],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Ring',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  
  id:31,
  image:['/images/accessories/Junwei Replacement Beaded Bracelet for Apple Watch Band 41mm,40mm,38mm,45mm,44mm,42mm,Adjustable Stylish Bands with Bling Rhinestones,Crystal,Pearls for iWatch Series 7,6,SE,5,4,3,2,1,Women,Girls.jpg'],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Beaded-Bracelet',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  
  id:32,
  image:['/images/accessories/Our Favorite Things on Sale to Buy for Your Wedding - Bridal Musings.jpg'],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Beaded',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  
  id:33,
  image:['/images/accessories/Promise Rings_ 22 The Most Popular Ring Ideas For Your Love.jpg'],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Promise-Ring',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  
  id:34,
  image:["/images/accessories/Silver Double Butterfly Pendant Clavicle Chain Women'S Necklace Jewelry Gift, Adult Unisex, Size_One size, Gold.jpg"],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Butterfly-Pendent',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  
  id:35,
  image:["/images/accessories/Unbranded _ 4 Pc Rhinestone Ring Size 7-9 Jewelry Set.jpg"],
  title:'Bracelet in Solid',
  description:'Butterfly Bracelet inSolid Sterling Purple , Green or yellow ',
  price:200,
  category:'Accessories',
  slug:'Rhinestone-Ring',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:60,
  uID:''
},
{
  id:36,
  image:["/images/shoes/download (13).jpg"],
  title:'Mehron Fancy Shoes',
  description:'Top Notch Shoes for Women',
  price:100,
  category:'Shoes',
  slug:'Shiny-Shoes',
  size:['5', '6','6.5','7','7.5','8'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
  
},
{
  id:37,
  image:["/images/shoes/Joskaa  2022 Women Shoe Designer Pump Square Heel for Summer Dancing Party Wedding Sandal Chaussure - Apricot _ 38.jpg"],
  title:'Mehron Fancy Shoes',
  description:'Top Notch Shoes for Women',
  price:100,
  category:'Shoes',
  slug:'Pump-Square-Heel',
  size:['5', '6','6.5','7','7.5','8'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
  
},
{
  id:38,
  image:["/images/shoes/Rhinestone Decor Point Toe Back Zipper Flats.jpg"],
  title:'Mehron Fancy Shoes',
  description:'Top Notch Shoes for Women',
  price:100,
  category:'Shoes',
  slug:'Point-Toe-Back-Zipper-Flats',
  size:['5', '6','6.5','7','7.5','8'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
  
},
{
  id:39,
  image:["/images/shoes/Shop Vintage Outfits __ Vintage Style Clothing __ ModCloth™ (1).jpg"],
  title:'Mehron Fancy Shoes',
  description:'Top Notch Shoes for Women',
  price:100,
  category:'Shoes',
  slug:'Vintage-Shoes',
  size:['5', '6','6.5','7','7.5','8'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
  
},
{
  id:40,
  image:["/images/shoes/Shop Vintage Outfits __ Vintage Style Clothing __ ModCloth™.jpg"],
  title:'Mehron Fancy Shoes',
  description:'Top Notch Shoes for Women',
  price:100,
  category:'Shoes',
  slug:'Vintage-Style-Shoes',
  size:['5', '6','6.5','7','7.5','8'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
  
},
{
  id:41,
  image:["/images/shoes/Women's Shoes, Heels, Boots _ Modcloth.jpg"],
  title:'Mehron Fancy Shoes',
  description:'Top Notch Shoes for Women',
  price:100,
  category:'Shoes',
  slug:'Vintage-Style-Boots',
  size:['5', '6','6.5','7','7.5','8'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount:40,
  uID:''
  
},
{
  id:42,
  image:['/images/t-shirts/6.jpg'],
  title:'Blue Check Line T-Shirt',
  description:'Best Qualiy T-shirt for Women',
  price:100,
  category:'T-Shirts',
  slug:'tShirt',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount: 30,
  uID: ''
},
{
  id:43,
  image:['/images/t-shirts/6.jpg'],
  title:'Blue Check Line T-Shirt',
  description:'Best Qualiy T-shirt for Women',
  price:100,
  category:'T-Shirts',
  slug:'tShirts',
  size:['S', 'M','L','XL'],
  color:['#ffffff','#000000','#e60000'],
  quantity:1,
  discount: 30,
  uID: ''
},
]
    

  

    
